# Generated by Django 4.1.7 on 2023-04-03 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
                name='Answer',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Pub date')),
                    ('rating', models.PositiveIntegerField(default=0, editable=False, verbose_name='Rating')),
                    ('text', models.TextField(verbose_name='Text')),
                    ('is_right', models.BooleanField(default=False, verbose_name='Best')),
                    ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers',
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ],
                options={
                    'abstract': False,
                },
        ),
        migrations.CreateModel(
                name='Question',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Pub date')),
                    ('rating', models.PositiveIntegerField(default=0, editable=False, verbose_name='Rating')),
                    ('title', models.CharField(db_index=True, help_text='Title', max_length=254,
                                               verbose_name='Title')),
                    ('text', models.TextField(help_text='Text', verbose_name='Text')),
                    ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions',
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ],
                options={
                    'abstract': False,
                },
        ),
        migrations.CreateModel(
                name='Tag',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('title', models.CharField(max_length=48, unique=True, verbose_name='Tag')),
                ],
        ),
        migrations.CreateModel(
                name='Vote',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='answer_votes', to='hasker.answer')),
                    ('author',
                     models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                    ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='question_votes', to='hasker.question')),
                ],
        ),
        migrations.CreateModel(
                name='UserProfile',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('avatar', models.ImageField(blank=True, default='images/profile/default.jpg', max_length=500,
                                                 upload_to='images/profile', verbose_name='Аватар')),
                    ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                                  to=settings.AUTH_USER_MODEL)),
                ],
        ),
        migrations.AddField(
                model_name='question',
                name='tags',
                field=models.ManyToManyField(blank=True, related_name='questions', to='hasker.tag'),
        ),
        migrations.AddField(
                model_name='answer',
                name='question',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers',
                                        to='hasker.question', verbose_name='Question'),
        ),
        migrations.AddConstraint(
                model_name='vote',
                constraint=models.UniqueConstraint(fields=('author', 'question'), name='unique_vote_user_question'),
        ),
        migrations.AddConstraint(
                model_name='vote',
                constraint=models.UniqueConstraint(fields=('author', 'answer'), name='unique_vote_user_answer'),
        ),
    ]
