name: Flake and tests

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name : run flake8
        run: flake8 01_advanced_basics/homework/log_analyzer --max-line-length 120
      - name: run tests
        run: python 01_advanced_basics/homework/log_analyzer/test_analyzer.py
      - name: run tests hw_03
        run: python 03_0_oop/homework/test.py