name: Flake and tests

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/chechout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: ["3.10", "3.11"]
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name : run flake8
        run: flake8 otus-python-pro/01_advanced_basics/homework/log_analyzer --max-line-length 120
      - name: run tests
        run: python otus-python-pro/01_advanced_basics/homework/log_analyzer/test_analyzer.py
